export const ADMIN_SIGNUP_BEGIN = 'ADMIN_SIGNUP_BEGIN';
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS';
export const ADMIN_SIGNUP_FAIL = 'ADMIN_SIGNUP_FAIL';

export const ADMIN_SIGNIN_BEGIN = 'ADMIN_SIGNIN_BEGIN';
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL';

export const ADMIN_SIGNOUT = 'ADMIN_SIGNOUT';
