export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';

export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';

export const LOAD_ITEMS_BEGIN = 'LOAD_ITEMS_BEGIN';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_FAIL = 'LOAD_ITEMS_FAIL';

export const LOAD_ITEM_DETAIL_BEGIN = 'LOAD_ITEM_DETAIL_BEGIN';
export const LOAD_ITEM_DETAIL_SUCCESS = 'LOAD_ITEM_DETAIL_SUCCESS';
export const LOAD_ITEM_DETAIL_FAIL = 'LOAD_ITEM_DETAIL_FAIL';

export const LOAD_ITEM_COUNT = 'LOAD_ITEM_COUNT';