export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';

export const LOAD_ITEMS_BEGIN = 'LOAD_ITEMS_BEGIN';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_FAIL = 'LOAD_ITEMS_FAIL';

export const LOAD_ITEM_DETAIL_BEGIN = 'LOAD_ITEM_DETAIL_BEGIN';
export const LOAD_ITEM_DETAIL_SUCCESS = 'LOAD_ITEM_DETAIL_SUCCESS';
export const LOAD_ITEM_DETAIL_FAIL = 'LOAD_ITEM_DETAIL_FAIL';

export const LOAD_ITEM_COUNT = 'LOAD_ITEM_COUNT';