export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAIL = 'ADD_EMPLOYEE_FAIL';

export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL';

export const LOAD_EMPLOYEES_BEGIN = 'LOAD_EMPLOYEES_BEGIN';
export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const LOAD_EMPLOYEES_FAIL = 'LOAD_EMPLOYEES_FAIL';

export const LOAD_EMPLOYEE_COUNT = 'LOAD_EMPLOYEE_COUNT';

export const LOAD_SINGLE_EMPLOYEE_SUCCESS = 'LOAD_SINGLE_EMPLOYEE_SUCCESS';
export const LOAD_SINGLE_EMPLOYEE_FAIL = 'LOAD_SINGLE_EMPLOYEE_FAIL';
